use_frameworks!

target 'BLXQRCodeSDK_Example' do
  pod 'BLXQRCodeSDK', :path => '../'

  target 'BLXQRCodeSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
